import { useEffect,useState } from 'react';
import { collection,onSnapshot } from 'firebase/firestore';
import { Link } from 'react-router-dom';
import { db } from '../firebase';
import { useCampaign } from '../context/useCampaign';
export default function CampaignLobby(){
 const {campaign,campaignId,isDm,createCampaign,joinCampaignByCode,leaveCampaign}=useCampaign(); const [name,setName]=useState('Mi campaña'),[description,setDescription]=useState(''),[code,setCode]=useState(''),[players,setPlayers]=useState([]),[error,setError]=useState('');
 useEffect(()=>{if(!campaignId)return;return onSnapshot(collection(db,'campaigns',campaignId,'members'),s=>setPlayers(s.docs.map(d=>({id:d.id,...d.data()}))))},[campaignId]);
 if(campaign)return <section className="campaign-stitch"><header className="campaign-hero"><div><span className="stitch-kicker">{isDm?'PANEL DEL DM':'CAMPAÑA ACTIVA'}</span><h1>{campaign.name}</h1><p>{campaign.description||'Campaña D&D 2024'}</p></div><button className="stitch-secondary" onClick={leaveCampaign}>Cambiar campaña</button></header><div className="campaign-overview"><div className="campaign-emblem">◈</div><div><span className="stitch-kicker">CÓDIGO DE INVITACIÓN</span><strong>{campaign.inviteCode}</strong><p>Comparte este código con tus jugadores para que entren a la mesa.</p></div><button className="stitch-primary" onClick={()=>navigator.clipboard?.writeText(campaign.inviteCode)}>Copiar código</button></div><div className="campaign-grid"><section className="stitch-card"><div className="dm-section-head"><div><span className="stitch-kicker">GRUPO</span><h2>Compañía de aventureros</h2></div><span className="campaign-count">{players.length}/{campaign.maxPlayers||8}</span></div><div className="campaign-members">{players.map(p=><div className="campaign-member" key={p.id}><div className="member-glyph">{(p.displayName||p.email||'?').slice(0,1).toUpperCase()}</div><div><strong>{p.displayName||'Jugador'}</strong><span>{p.role==='dm'?'Dungeon Master':'Jugador'}</span></div>{p.id===campaign.dmUid&&<b>DM</b>}</div>)}</div></section><aside className="stitch-card campaign-side"><span className="stitch-kicker">ESTADO DE MESA</span><div className="campaign-metric"><b>{players.length}</b><span>Miembros</span></div><div className="campaign-metric"><b>{isDm?'DM':'PJ'}</b><span>Tu rol</span></div><Link className="stitch-primary full-width" to="/personajes">Mis personajes</Link>{isDm&&<Link className="stitch-secondary full-width" to="/dm">Abrir panel del DM</Link>}</aside></div></section>;
 return <section className="campaign-stitch campaign-join"><header className="campaign-hero"><div><span className="stitch-kicker">D&D 5E COMPANION · MESA</span><h1>Tu mesa de juego</h1><p>Crea una campaña como DM o únete mediante el código de invitación.</p></div></header><div className="campaign-create-grid"><section className="stitch-card"><span className="stitch-kicker">NUEVA CAMPAÑA</span><h2>Crear como Dungeon Master</h2><label className="stitch-field"><span>Nombre</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="La Mina Perdida"/></label><label className="stitch-field"><span>Descripción</span><textarea rows="4" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Una breve descripción de la aventura"/></label><button className="stitch-primary full-width" onClick={async()=>{try{setError('');await createCampaign(name,{description,maxPlayers:8})}catch(e){setError(e.message)}}}>⚔ Crear campaña</button></section><section className="stitch-card"><span className="stitch-kicker">INVITACIÓN</span><h2>Unirme a una campaña</h2><p>Introduce el código de 8 caracteres que te entregó tu DM.</p><label className="stitch-field"><span>Código</span><input value={code} maxLength="8" onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ABCD2345"/></label><button className="stitch-secondary full-width" onClick={async()=>{try{setError('');await joinCampaignByCode(code)}catch(e){setError(e.message)}}}>🎲 Unirme a la mesa</button></section></div>{error&&<div className="stitch-error">{error}</div>}</section>;
}