import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { CLASS_OPTIONS, SPECIES_OPTIONS, BACKGROUND_OPTIONS, ALIGNMENT_OPTIONS, ABILITY_GENERATION_OPTIONS } from '../data/characterOptions.js';
import { useCharacters } from '../context/useCharacters';
import { getClassData, getMasteryCount } from '../data/classData.js';

const STEPS=[['class','Clase'],['origin','Origen'],['abilities','Atributos'],['details','Detalles'],['gear','Equipo'],['finish','Confirmar']];
const stats=[['for','Fuerza','FUE'],['des','Destreza','DES'],['con','Constitución','CON'],['int','Inteligencia','INT'],['sab','Sabiduría','SAB'],['car','Carisma','CAR']];

export default function CharacterBuilder(){
 const navigate=useNavigate(); const {createCharacter}=useCharacters(); const [step,setStep]=useState(0); const [error,setError]=useState(''); const [creating,setCreating]=useState(false);
 const [data,setData]=useState({name:'',class:'',race:'',background:'',alignment:'',level:1,player:'',abilityMethod:'standard',stats:{for:15,des:14,con:13,int:12,sab:10,car:8},inventory:'',proficiencies:'',hitDice:'d10',equipmentChoice:'',masteryWeapons:[]});
 const set=p=>setData(v=>({...v,...p})); const setStat=(k,v)=>set({stats:{...data.stats,[k]:Number(v)}});
 const classInfo=useMemo(()=>getClassData(data.class),[data.class]);
 const masteryLimit=getMasteryCount(data.class,data.level);
 const toggleMastery=weapon=>set({masteryWeapons:data.masteryWeapons.includes(weapon)?data.masteryWeapons.filter(x=>x!==weapon):data.masteryWeapons.length<masteryLimit?[...data.masteryWeapons,weapon]:data.masteryWeapons});
 const selectClass=className=>{const info=getClassData(className);set({class:className,hitDice:info?.hitDie||'d10',proficiencies:info?[`Salvaciones: ${info.saves.join(', ')}`,`Armas: ${info.weapons}`,`Armaduras: ${info.armor}`,`Herramientas: ${info.tools}`].join('\\n'):'',equipmentChoice:'',inventory:'',masteryWeapons:[]});};
 const applyEquipment=choice=>{if(!classInfo)return;const item=classInfo.equipment[choice];set({equipmentChoice:choice,inventory:item||''});};
 const next=()=>{if(step===0&&!data.class)return setError('Selecciona una clase.');if(step===1&&(!data.race||!data.background))return setError('Selecciona especie y trasfondo.');if(step===3&&!data.name.trim())return setError('Escribe el nombre del personaje.');setError('');setStep(v=>Math.min(STEPS.length-1,v+1))};
 const finish=async()=>{if(creating)return;if(!data.name.trim())return setError('Escribe el nombre del personaje.');setCreating(true);setError('');try{const id=await createCharacter({...data,name:data.name.trim(),level:Number(data.level)||1,weaponMastery:{enabled:masteryLimit>0,weapons:data.masteryWeapons,limit:masteryLimit},classFeatures:classInfo?.level1Features||[]});navigate('/personaje/'+id,{replace:true});}catch(e){setCreating(false);setError(e?.message||'No se pudo crear el personaje.')}};
 return <section className="stitch-builder">
  <div className="stitch-builder-head"><div><Link to="/personajes" className="stitch-back">← Personajes</Link><span className="stitch-kicker">CONSTRUCTOR DE HÉROE · D&D 2024 / 5.5e</span><h1>Crea tu personaje</h1><p>Origen mecánico, dote, atributos, equipo y dominio de armas en una experiencia guiada.</p></div><div className="builder-mode"><button className="active">☷ Guiado</button><button>◈ Aleatorio</button><button>⚙ Avanzado</button></div></div>
  <div className="builder-stepper">{STEPS.map(([id,label],i)=><button key={id} className={i===step?'current':i<step?'done':''} onClick={()=>i<step&&setStep(i)}><b>{i<step?'✓':i+1}</b><span><small>{i+1}. {label}</small><strong>{i===0&&data.class||i===1&&data.background||i===2?'Configurar':i===3&&data.name||i===4?'Paquete y dominio':'Resumen'}</strong></span></button>)}</div>
  <div className="builder-layout"><main className="builder-main">
   {step===0&&<section className="stitch-card builder-card"><div className="builder-section-title"><span>⚔</span><div><span className="stitch-kicker">PASO 1</span><h2>Clase de personaje</h2><p>Elige la base de tus capacidades, competencias y estilo de combate.</p></div></div><div className="stitch-option-grid">{CLASS_OPTIONS.map(x=><button key={x} className={'stitch-choice '+(data.class===x?'selected':'')} onClick={()=>selectClass(x)}><span className="choice-icon">✦</span><strong>{x}</strong><small>Características y competencias</small>{data.class===x&&<em>✓ Elegida</em>}</button>)}</div>{classInfo&&<div className="class-profile"><div><b>Salvaciones</b><span>{classInfo.saves.join(' · ')}</span></div><div><b>Armas</b><span>{classInfo.weapons}</span></div><div><b>Armaduras</b><span>{classInfo.armor}</span></div><div><b>Rasgos de nivel 1</b><span>{classInfo.level1Features.join(' · ')}</span></div></div>}</section>}
   {step===1&&<section className="stitch-card builder-card"><div className="builder-section-title"><span>♜</span><div><span className="stitch-kicker">PASO 2 · ORIGEN 2024</span><h2>Trasfondo y especie</h2><p>El origen aporta identidad, competencias y dotes de nivel 1.</p></div></div><div className="origin-grid"><div><label className="stitch-field"><span>Especie</span><select value={data.race} onChange={e=>set({race:e.target.value})}><option value="">Seleccionar…</option>{SPECIES_OPTIONS.map(x=><option key={x}>{x}</option>)}</select></label><div className="micro-options">{SPECIES_OPTIONS.slice(0,5).map(x=><button className={data.race===x?'picked':''} key={x} onClick={()=>set({race:x})}>{x}</button>)}</div></div><div><label className="stitch-field"><span>Trasfondo</span><select value={data.background} onChange={e=>set({background:e.target.value})}><option value="">Seleccionar…</option>{BACKGROUND_OPTIONS.map(x=><option key={x}>{x}</option>)}</select></label><div className="micro-options">{BACKGROUND_OPTIONS.slice(0,5).map(x=><button className={data.background===x?'picked':''} key={x} onClick={()=>set({background:x})}>{x}</button>)}</div></div><label className="stitch-field"><span>Alineamiento</span><select value={data.alignment} onChange={e=>set({alignment:e.target.value})}><option value="">Seleccionar…</option>{ALIGNMENT_OPTIONS.map(x=><option key={x}>{x}</option>)}</select></label></div></section>}
   {step===2&&<section className="stitch-card builder-card"><div className="builder-section-title"><span>♢</span><div><span className="stitch-kicker">PASO 3 · CARACTERÍSTICAS</span><h2>Distribuye tus atributos</h2><p>Método actual: {ABILITY_GENERATION_OPTIONS.find(x=>x.value===data.abilityMethod)?.label}</p></div></div><label className="stitch-field method-field"><span>Método de generación</span><select value={data.abilityMethod} onChange={e=>set({abilityMethod:e.target.value})}>{ABILITY_GENERATION_OPTIONS.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><div className="builder-stat-grid">{stats.map(([k,l,a])=><label className="builder-stat-pod" key={k}><span>{a}</span><strong>{data.stats[k]}</strong><input type="range" min="1" max="20" value={data.stats[k]} onChange={e=>setStat(k,e.target.value)}/><em>{Math.floor((data.stats[k]-10)/2)>=0?'+':''}{Math.floor((data.stats[k]-10)/2)}</em><small>{l}</small></label>)}</div></section>}
   {step===3&&<section className="stitch-card builder-card"><div className="builder-section-title"><span>✎</span><div><span className="stitch-kicker">PASO 4 · IDENTIDAD</span><h2>Detalles del héroe</h2><p>Estos datos aparecerán en la cabecera de tu hoja.</p></div></div><div className="details-grid"><label className="stitch-field"><span>Nombre del personaje</span><input autoFocus value={data.name} onChange={e=>set({name:e.target.value})} placeholder="Ej. Arannis Valen"/></label><label className="stitch-field"><span>Jugador</span><input value={data.player} onChange={e=>set({player:e.target.value})} placeholder="Tu nombre"/></label><label className="stitch-field"><span>Nivel</span><input type="number" min="1" max="20" value={data.level} onChange={e=>set({level:Number(e.target.value)})}/></label><label className="stitch-field"><span>Dado de golpe</span><input value={data.hitDice} onChange={e=>set({hitDice:e.target.value})}/></label></div></section>}
   {step===4&&<section className="stitch-card builder-card"><div className="builder-section-title"><span>◈</span><div><span className="stitch-kicker">PASO 5 · EQUIPO Y MAESTRÍA</span><h2>Prepara tu equipo</h2><p>El equipo inicial, competencias y Maestría de armas se cargan según la clase 2024.</p></div></div>{classInfo?<><div className="class-gear-summary"><div><span>Competencias</span><strong>{classInfo.weapons}</strong></div><div><span>Armaduras</span><strong>{classInfo.armor}</strong></div><div><span>Herramientas</span><strong>{classInfo.tools}</strong></div><div><span>Dado de golpe</span><strong>{classInfo.hitDie}</strong></div></div><div className="gear-presets">{classInfo.equipment.map((item,i)=><button className={data.equipmentChoice===String.fromCharCode(65+i)?'picked':''} key={item} onClick={()=>applyEquipment(i)}>{item}</button>)}</div><label className="stitch-field"><span>Equipo inicial / inventario</span><textarea rows="6" value={data.inventory} onChange={e=>set({inventory:e.target.value})} placeholder="Armas, armadura, herramientas y tesoros…"/></label><div className="mastery-box"><div className="mastery-head"><div><span className="stitch-kicker">MAESTRÍA DE ARMAS 2024</span><h3>{masteryLimit?'Elige hasta '+masteryLimit+' armas':'Esta clase no obtiene Maestría de armas a nivel '+data.level}</h3></div><b>{data.masteryWeapons.length}/{masteryLimit}</b></div>{masteryLimit>0?<div className="mastery-grid">{classInfo.masteryPool.map(weapon=><button type="button" key={weapon} className={data.masteryWeapons.includes(weapon)?'picked':''} onClick={()=>toggleMastery(weapon)} disabled={!data.masteryWeapons.includes(weapon)&&data.masteryWeapons.length>=masteryLimit}>{weapon}</button>)}</div>:<p className="muted">La Maestría de armas se muestra cuando la clase obtiene el rasgo correspondiente.</p>}</div><label className="stitch-field"><span>Competencias y dominio de armas</span><textarea rows="5" value={data.proficiencies} onChange={e=>set({proficiencies:e.target.value})} placeholder="Competencias calculadas según clase…"/></label></>:<p className="muted">Selecciona una clase para cargar su equipo, competencias y Maestrías.</p>}</section>}
   {step===5&&<section className="stitch-card builder-card finish-card"><div className="hero-preview"><div className="preview-avatar">{(data.name||'?').slice(0,1).toUpperCase()}</div><div><span className="stitch-kicker">HÉROE LISTO</span><h2>{data.name||'Sin nombre'}</h2><p>{[data.race,data.class].filter(Boolean).join(' · ')||'Sin origen configurado'}</p><small>Nivel {data.level} · {data.background||'Sin trasfondo'} · {data.alignment||'Sin alineamiento'}</small></div></div><div className="preview-stats">{stats.map(([k,l,a])=><div key={k}><span>{a}</span><strong>{data.stats[k]}</strong><small>{l}</small></div>)}</div><div className="finish-notice">✦ Se guardará en Firebase y podrás editarlo desde la hoja de personaje.</div></section>}
  </main><aside className="builder-preview stitch-card"><span className="stitch-kicker">VISTA PREVIA</span><div className="preview-orb">{(data.name||'H').slice(0,1).toUpperCase()}</div><h3>{data.name||'Nuevo héroe'}</h3><p>{[data.race,data.class].filter(Boolean).join(' · ')||'Selecciona clase y especie'}</p><div className="preview-line"><span>NIVEL</span><b>{data.level}</b></div><div className="preview-line"><span>TRASFONDO</span><b>{data.background||'—'}</b></div><div className="preview-line"><span>CAMPAÑA</span><b>Sin campaña</b></div><div className="preview-ability-row">{stats.map(([k,,a])=><div key={k}><span>{a}</span><b>{data.stats[k]}</b></div>)}</div></aside></div>
  {error&&<div className="stitch-error">{error}</div>}<div className="builder-actions-stitch">{step>0?<button className="stitch-secondary" disabled={creating} onClick={()=>{setError('');setStep(v=>v-1)}}>← Atrás</button>:<span/>}{step<STEPS.length-1?<button className="stitch-primary" onClick={next}>Continuar →</button>:<button className="stitch-primary" disabled={creating} onClick={finish}>{creating?'Creando…':'Crear personaje'}</button>}</div>
 </section>;
}