import { Link } from 'react-router-dom';
import { useCharacters } from '../context/useCharacters';
export default function CharacterManager(){
 const {characters,activeCharacterId,deleteCharacter,duplicateCharacter,selectCharacter}=useCharacters();
 return <section className="vault-page">
  <div className="vault-hero"><div><span className="stitch-kicker">D&D 5E COMPANION · BÓVEDA</span><h1>Mis personajes</h1><p>Tu colección de héroes, lista para entrar en cualquier campaña.</p></div><Link className="stitch-primary" to="/personajes/nuevo">✦ Crear personaje</Link></div>
  <div className="vault-toolbar"><div><b>{characters.length}</b><span>Personajes</span></div><div className="vault-toolbar-note">Persistencia en Firebase · selección activa sincronizada</div></div>
  {characters.length===0?<div className="vault-empty stitch-card"><div className="empty-die">d20</div><span className="stitch-kicker">NUEVA AVENTURA</span><h2>Tu primera hoja empieza aquí</h2><p>Crea un héroe con el constructor D&D 2024 y después podrás editar sus atributos, equipo, hechizos y notas.</p><Link className="stitch-primary" to="/personajes/nuevo">Crear mi primer personaje</Link></div>:<div className="vault-grid">{characters.map(c=><article className={'vault-card stitch-card '+(activeCharacterId===c.id?'active':'')} key={c.id}><div className="vault-art"><span>{(c.name||'?').slice(0,1).toUpperCase()}</span><small>NIV. {c.level||1}</small></div><div className="vault-body"><div className="vault-card-top"><span className="stitch-kicker">{c.campaignId?'EN CAMPAÑA':'SIN CAMPAÑA'}</span>{activeCharacterId===c.id&&<b>ACTIVO</b>}</div><h2>{c.name||'Sin nombre'}</h2><p>{[c.race,c.class,c.subclass].filter(Boolean).join(' · ')||'Personaje sin configurar'}</p><div className="vault-vitals"><span><small>PG</small>{c.hp?.actual??10}/{c.hp?.max??10}</span><span><small>CA</small>{c.ac??10}</span><span><small>INIC</small>{c.initiative>=0?'+':''}{c.initiative??0}</span></div><div className="vault-actions"><Link className="stitch-primary" to={'/personaje/'+c.id} onClick={()=>selectCharacter(c.id)}>Abrir hoja</Link><button className="stitch-secondary" onClick={()=>duplicateCharacter(c)}>Duplicar</button><button className="danger-action" onClick={()=>{if(window.confirm('¿Eliminar a '+(c.name||'este personaje')+'?'))deleteCharacter(c.id)}}>×</button></div></div></article>)}</div>}
 </section>
}